### ISSUE TITLE
github action을 이용한 배포

### ISSUE THREAD

**Issue by rkolx** [HJKL2022/backend#6]
## 📃 Description
github action을 이용하여 배포를 한다.

## ☑ Todo
- [x] build.gradle 변경
- [x] Dokcerfile 작성
- [x] workflows 스크립트 작성
- [x] secret key 생성
